name: Build documentation and publish

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate the documentation
        uses: ./.github/actions/generate-docs
        with:
          symlink-name: sample_docs
          docs-directory: docs
          documentation-format: html
      - name: Publish the documentation
        uses: ./.github/actions/publish-docs
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'docs/build/html'
          destination-github-username: 'alartum'
          destination-repository-name: 'alartum.github.io'
          user-email: noreply@gmail.com
          target-branch: main
          target-directory: sample_docs
